### PR TITLE
all: add cpu profiling support and improve stats computations

### PR DESCRIPTION
**Pull request by rjl493456442**
This PR adds and fixes a few things.

- Add PProf web interface for debugging
- Add CPU PProf for internal profiling
- Fix bench stat tool
- Fix bench plot tool

### CODE REVIEW

**Comment by rjl493456442** [comment]
image

image

**Comment by rjl493456442** [comment]
The new render is more explicit. We can find the second chart has HUGE performance fluctuation while the first one is kind of stable.

**Comment by rjl493456442** [comment]
For bench stat, the original is incorrect.

With the fix 

```
-- concurrent-30gb (52428 events) total time: 992.2488s
 total size: 32211763200 bytes
  mean mb/s: 30.960 (+- 4.446)
```

```
-- batch-100kb.2020-07-13-20:45:10 (853 events) total time: 184.0734s
 total size: 524083200 bytes
  mean mb/s: 2.715 (+- 7.370)
```

**Comment by fjl** [comment]
I have merged the ldb-benchstat fix. I don't want to merge the other changes because they are so invasive. Regarding the plot changes, the original idea behind the benchmark tool was checking if the write speed gets slower when the DB size increases. This is why the X axis of the plot is the DB size, it makes different runs more comparable. There is also the abstime plot type (CLI option `-plot abstime`) to see the speed in a different way.

**Pull request closed without merging**
